---
version: "2"
services:
    www:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.28
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: Project
            MYSQL_USER: root
            MYSQL_PASSWORD: abcd1234
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - .project.sql:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
            - .:/var/www/html/
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 82:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: abcd1234
            MYSQL_ROOT_PASSWORD: admin
volumes:
    persistent:
