version: '3.9'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: project
      MYSQL_USER: akshay
      MYSQL_PASSWORD: akshay
    networks:
      - app_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "9000:80"
    environment:
      PMA_HOST: mysql-db
      PMA_USER: akshay
      PMA_PASSWORD: akshay
    networks:
      - app_net

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app_container
    ports:
      - "80:80"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
