version: '3.9'

services:
  # PHP Service
  php:
    image: php:latest
    container_name: php_container
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app_net

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: iims-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - project.sql:/var/lib/mysql
    networks:
      - app_net

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: admin 
    networks:
      - app_net

volumes:
  mysql_data:

networks:
  app_net:
    driver: bridge
